# Generated by Django 3.1.7 on 2021-03-11 23:56

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210311_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(upload_to=posts.models.user_directory_path),
        ),
    ]
